---
- hosts: all
  become: yes
  pre_tasks:
    - name: Get OS version
      debug:
        var: ansible_distribution_version
  roles:
    - role: xenial-cis
      vars:
        ubuntu1604cis_ignore_remount_errors: true
      when: ansible_distribution_version == '16.04'
    - role: bionic-cis
      vars:
        ubuntu1804cis_ignore_remount_errors: true
      when: ansible_distribution_version == '18.04'
    - role: amazon2-cis
      when:
        - ansible_distribution == 'Amazon'
        - ansible_distribution_major_version == '2'
    - scaleft-agent
    - awscli
  tasks:
    - name: Ensure packages are installed
      apt:
        name:
          - jq
          - nano
          - curl
        state: present
