---
- src: florianutz.ubuntu1604-cis
  version: "2.0.3"
  name: xenial-cis
- src: florianutz.ubuntu1804_cis
  version: "1.2.2"
  name: bionic-cis
- src: https://github.com/rhythmictech/cis-amazon-linux-2
  version: "1.0.5"
  name: amazon2-cis
- src: https://github.com/rhythmictech/ansible-scaleft-agent
  version: "1.1.2"
  name: scaleft-agent
- src: geerlingguy.repo-epel
  version: "1.2.4"
- src: geerlingguy.pip
  version: "1.3.0"
- src: https://github.com/rhythmictech/ansible-role-awscli
  version: "1.0.2"
  name: awscli
