---
- src: https://github.com/rhythmictech/Ubuntu1604-CIS.git
  version: "2.1.0"
  name: xenial-cis
- src: https://github.com/rhythmictech/Ubuntu1804-CIS.git
  version: "2.1.0"
  name: bionic-cis
- src: anthcourtney.cis-amazon-linux
  version: "1.1.6"
  name: amazon2-cis
- src: https://github.com/rhythmictech/ansible-scaleft-agent
  version: "1.1.1"
  name: scaleft-agent
- src: geerlingguy.repo-epel
  version: "1.2.3"
- src: geerlingguy.pip
  version: "1.3.0"
