---
- src: https://github.com/rhythmictech/ansible-scaleft-agent
  version: "1.1.2"
  name: scaleft-agent
- src: geerlingguy.repo-epel
  version: "1.2.4"
- src: geerlingguy.pip
  version: "1.3.0"
- src: https://github.com/rhythmictech/ansible-role-awscli
  version: 1.0.0
  name: awscli
