---
- hosts: all
  become: yes
  roles:
  - role: packer
    vars:
      packer_version: "1.4.0"
  - ansible
  - awscli
  - scaleft-agent
  tasks:
  - name: Ensure packages are installed
    apt:
      name:
      - jq
      - nano
      - curl
      state: present
