- src: geerlingguy.packer
  version: "1.0.1"
  name: packer

- src: geerlingguy.ansible
  version: "2.0.1"
  name: ansible

- src: geerlingguy.repo-epel
  version: "1.2.3"

- src: geerlingguy.pip
  version: "1.3.0"

- src: https://github.com/rhythmictech/ansible-scaleft-agent
  version: "1.1.0"
  name: scaleft-agent
